application: facebook-radio-practice
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /js
  static_dir: js
- url: /player
  static_files: player.html
  upload: player.html
- url: /fblogin
  static_files: fblogin.html
  upload: fblogin.html
- url: /
  script: main.app