application: facebook-radio-practice
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /player
  static_files: player.html
  upload: player.html
- url: /.*
  static_files: index.html
  upload: index.html